### ISSUE TITLE
Tweets not sent

### ISSUE THREAD

**Issue by taktran** [pebblecode/tricklrapp.com#97]
> @tricklr @pebblecode Help! My tweets are caught in the Tricklr. They flash in my queue for a second with negative times, then disappear.

[@facts_n_quotes](https://twitter.com/facts_n_quotes/) (id 2837)

May be related to #95 
## TODO
- [x] Upgrade twitter gem
- [ ] Get capistrano deployment working
- [ ] Add campfire notifications back in (add tinder - https://github.com/collectiveidea/tinder/pull/57). Also see https://github.com/pebblecode/tricklrapp.com/commit/782de66ab5a9ba45994d09f357787b8a712f35bc
